# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logging_framework/protobuf/apilog.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\'logging_framework/protobuf/apilog.proto\x12\x06\x61pilog"\xfd\x01\n\x06\x41piLog\x12\x19\n\x11request_timestamp\x18\x01 \x01(\x03\x12\x14\n\x0c\x61pi_endpoint\x18\x02 \x01(\t\x12\x13\n\x0bhttp_method\x18\x03 \x01(\t\x12\x13\n\x0bstatus_code\x18\x04 \x01(\x05\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\x15\n\rerror_message\x18\x06 \x01(\t\x12\x12\n\nlatency_ms\x18\x07 \x01(\x01\x12,\n\x07\x63ontext\x18\x08 \x03(\x0b\x32\x1b.apilog.ApiLog.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"\x91\x01\n\x08\x41piBatch\x12\x1d\n\x15\x62\x61tch_start_timestamp\x18\x01 \x01(\x03\x12\x1b\n\x13\x62\x61tch_end_timestamp\x18\x02 \x01(\x03\x12\x13\n\x0binstance_id\x18\x03 \x01(\t\x12\x16\n\x0e\x62\x61tch_sequence\x18\x04 \x01(\x03\x12\x1c\n\x04logs\x18\x05 \x03(\x0b\x32\x0e.apilog.ApiLogb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "logging_framework.protobuf.apilog_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_APILOG_CONTEXTENTRY"]._options = None
    _globals["_APILOG_CONTEXTENTRY"]._serialized_options = b"8\001"
    _globals["_APILOG"]._serialized_start = 52
    _globals["_APILOG"]._serialized_end = 305
    _globals["_APILOG_CONTEXTENTRY"]._serialized_start = 259
    _globals["_APILOG_CONTEXTENTRY"]._serialized_end = 305
    _globals["_APIBATCH"]._serialized_start = 308
    _globals["_APIBATCH"]._serialized_end = 453
# @@protoc_insertion_point(module_scope)
