timeseries:
  retention:
    value: '120'
    unit: days
industry: oil_gas
document_processing:
  document_types:
    sol:
      document_type: SOL
      source_columns:
      - Process System
      - Equipment Name
      - Threat and consequence
      - Instrument Tag No.
    bncpp:
      document_type: bncpp
      source_columns:
      - Main Equipment
      - Tag No.
      - Description
