timeseries:
  retention:
    value: '90'
    unit: days
industry: oil_gas
document_processing:
  document_types:
    sol:
      document_type: SOL
      source_columns:
      - Process System
      - Equipment Name
      - Threat and consequence
