"""The deterministic ontology id survives a write that a serial primary key would discard."""

from __future__ import annotations

import os
import pathlib

os.environ.setdefault("AWS_ACCESS_KEY_ID", "test")
os.environ.setdefault("AWS_SECRET_ACCESS_KEY", "test")

import yaml

from p0.api.database.cdm_writer import _carry_ontology_uid

COMMON = (
    pathlib.Path(__file__).resolve().parents[2] / "config" / "templates" / "_common"
)
SCHEMA = yaml.safe_load((COMMON / "schema.yaml").read_text())["schema"]
ONTOLOGY = yaml.safe_load((COMMON / "ontology_template.yaml").read_text())
META = {"ontology_uid": "character varying", "equipment_uid": "bigint"}
SERIAL = {"equipment_uid"}


def _entities():
    def walk(node):
        if isinstance(node, dict):
            if "table" in node and "id_column" in node:
                yield node
            for value in node.values():
                yield from walk(value)
        elif isinstance(node, list):
            for value in node:
                yield from walk(value)

    return [e for e in walk(ONTOLOGY) if e["table"] in SCHEMA]


def test_every_ontology_table_can_hold_a_deterministic_id():
    missing = [
        e["table"]
        for e in _entities()
        if "ontology_uid" not in SCHEMA[e["table"]].get("columns", {})
    ]
    assert not missing, f"tables that would still discard their id: {missing}"


def test_the_column_is_wide_enough_for_the_hash():
    declared = SCHEMA["equipment"]["columns"]["ontology_uid"]
    assert int(declared[len("VARCHAR(") : -1]) >= 45


def test_a_hash_in_a_serial_column_is_carried_across():
    out = _carry_ontology_uid([{"equipment_uid": "eq:abc123"}], META, SERIAL)
    assert out[0]["ontology_uid"] == "eq:abc123"


def test_a_sequence_number_is_not_mistaken_for_an_identity():
    out = _carry_ontology_uid([{"equipment_uid": "4471"}], META, SERIAL)
    assert not out[0].get("ontology_uid")


def test_an_existing_identity_is_never_overwritten():
    out = _carry_ontology_uid(
        [{"equipment_uid": "eq:abc", "ontology_uid": "already"}], META, SERIAL
    )
    assert out[0]["ontology_uid"] == "already"


def test_a_table_without_the_column_is_left_alone():
    out = _carry_ontology_uid([{"equipment_uid": "eq:abc"}], {"equipment_uid": "bigint"}, SERIAL)
    assert "ontology_uid" not in out[0]


def test_nothing_is_carried_when_no_column_is_autogenerated():
    out = _carry_ontology_uid([{"equipment_uid": "eq:abc"}], META, set())
    assert "ontology_uid" not in out[0]


def test_the_original_rows_are_not_mutated():
    rows = [{"equipment_uid": "eq:abc"}]
    _carry_ontology_uid(rows, META, SERIAL)
    assert "ontology_uid" not in rows[0]
